name: Build

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build wheels
        run: pip wheel --wheel-dir ./dist --no-deps .

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.whl
